---  # 每個 --- 下表示一個檔案，就好像好幾個 yml 檔案合併在一起
server:
  port: 9999  # :後面一定要空格

---
m:
  wk:
    id: 222
    name: 孫悟空
    date-time: 2000/10/10 10:00:00
    iArray: [ 111, 222 ]  # YAML 的陣列、list、set 有兩種寫法
    ls:
      - aaa
      - bbb
      - |  # 後面一定要換行，| 類似 HTML 的 <pre>，打什麼都會保留
        a1
        b2
        c3
      - >  # 後面一定要換行，> 會將換行改成空格，但每行開頭不能有空格，否則和 | 效果一樣
        a1
        b2
        c3
    set: [ bbb, bbb ]
    dogs: # YAML 的 物件、map 有兩種寫法
      - id: 100
        name: 柯基
      - { id: 200, name: 柴犬 }
    dogMap:
      a:
        id: 100
        name: '柯 \n 基'  # 字串可用 ‘ 或 “ 包起來，在 YAML 裡，只有 “ 裡的 \n 會換行
      b:
        { id: 200, name: "柴 \n 犬" }

